name: Kubernets

on:
  workflow_call:

jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurando Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - run: git clone https://github.com/jnadyr/Infra_CI_Kubernetes.git


    - name: HashiCorp - Setup Terraform # Instala o Terraform no runner
      uses: hashicorp/setup-terraform@v2.0.3

    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init #inicia o Terraform

#    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve #destroi a infraestrutura
#    - run: return 1
      
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve  # aplica o Terraform

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      with:
        # Version of kubectl
        version: latest

    - run: aws sts get-caller-identity # comando proveniente da documentação da AWS

    - run: aws eks update-kubeconfig --region us-east-2 --name homolog2  # Cria arquivo kubeconfig automaticamente       

    - run: kubectl get svc # testa a configuração

 #   - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog destroy -auto-approve  # desfaz a infra criada com o Terraform   
