name: Teste de Carga

on:
  workflow_call:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurando Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - run: git clone https://github.com/jnadyr/Infra_CI.git # Clona o Terraform para criar e destruir a infra

    - name: HashiCorp - Setup Terraform # Instala o Terraform no runner
      uses: hashicorp/setup-terraform@v2.0.3

    - run: terraform -chdir=Infra/CI/env/Homolog init #inicia o Terraform
    
    - run: terraform -chdir=Infra/CI/env/Homolog destroy # remove qq infra que, por acaso, tenha ficado ativa.

    - run: terraform -chdir=Infra/CI/env/Homolog apply -auto-approve  # aplica o Terraform 

    - run: echo "$(terraform -chdir=Infra/CI/env/Homolog output -raw IP_alb)" # Executa o parêntesis e joga a saída para o terminal

    
  
